### ISSUE TITLE
[in private testing] [Work in Progress] Fix the bot.

### ISSUE THREAD

**Issue by itskaje** [shiftcodeYT/PokeBot3#123] opened 2016-08-03 20:30 UTC
i put my location as NY cental park right in the middle of it.... and it says it cant find any pokestops in a range of 5000m?

**Comment by DirtbikeKing247** [comment] 2016-08-03 20:36
Same issue 
![pkm_error](https://cloud.githubusercontent.com/assets/14851882/17381103/4c7193d4-5998-11e6-9789-a0c238a0940d.png)

**Comment by H1337er** [comment] 2016-08-03 20:48
had to update my version on my noxplayer think it might relate to this?

**Comment by itskaje** [comment] 2016-08-03 20:49
i dont think noxplayer has anything to do with this bot not working properly

**Comment by shiftcodeYT** [comment] 2016-08-03 20:50
@itskaje No, niantic updated the API. I'll have to fix it tomorrow.

**Comment by itskaje** [comment] 2016-08-03 20:52
@shiftcodeYT oh. sounds good.

**Comment by sidg2681** [comment] 2016-08-03 22:19
so i guess everyones in central park then

**Comment by sidg2681** [comment] 2016-08-03 22:35
also if u remember initially when u started this bot u had an idea to make 2 modes
one xp bot and a farm bot
well i have gotten a xp bot sorto working
hoping u can implement it if its stable
although frankly i just used auto clicker on pc to get this done to just farm pokestops nonstop abt 1 pokestop per second
and the result was i almost  hit lvl 7 in 5 mins b4 it crashed
but the xp per when calculted would be around 150k
if u think u can make it work in this bot pls llemme know
i used the tutu bot in  nox on pc and ran him at 100kmph to all the pokestops around new york central park using prenoted coordinates
funny thing is i didnt get banned and all ii have is a bulbasur and i am almost lvl 7

**Comment by mephistophaIes** [comment] 2016-08-04 10:07
Any news?

**Comment by shiftcodeYT** [comment] 2016-08-04 10:08
Not yet

**Comment by WhySoSerious21** [comment] 2016-08-04 10:11
Can u estimate when it'll be launched? Tomorrow? Thx..

**Comment by mephistophaIes** [comment] 2016-08-04 10:54
still not working

**Comment by tiny1980** [comment] 2016-08-04 12:56
At the moment no bots are working (at least not as before).
Some are reporting needing a full re-work.
We'll have to be patient, as it may be longer then expected.

Many devs are working together to try and find the best possible workarounds, although I would be surprised if it gets fixed in the next 24hrs.  I'm always hopeful though!

**Comment by DirtbikeKing247** [comment] 2016-08-04 13:31
Apparently they have added a MapObjects checksum encryption (AES)
Just need to find the key and they are good to go..

**Comment by Jzitko** [comment] 2016-08-04 13:51
Thank you for all of your hard work.  I picture a group of highly skilled API and AES devs working through some "mr robot" style chat system to get this shit done.

**Comment by NurdinA** [comment] 2016-08-04 14:57
still dont working

**Comment by shiftcodeYT** [comment] 2016-08-04 14:57
@NurdinA Did i say i fixed it?

**Comment by itskaje** [comment] 2016-08-04 14:58
@Jzitko its most likely just one person  (shiftcodeYT) thats working on it.  Or if you look to the right of your screen you'll see the "Assignees" only 3 people.

**Comment by Bulangseng** [comment] 2016-08-04 16:47
any news guys?

**Comment by ShitsMoneyOnBotDevs** [comment] 2016-08-04 17:11
If you can fix the bug, I will drown you in donations.

**Comment by Jesusmy2016** [comment] 2016-08-04 17:12
I encourage fellow

**Comment by JustinCR20** [comment] 2016-08-04 19:16
any fix?

**Comment by shiftcodeYT** [comment] 2016-08-04 19:16
@JustinCR20 no.

**Comment by JustinCR20** [comment] 2016-08-04 19:17
lol

**Comment by Shankky14** [comment] 2016-08-04 19:50
When the api is fixed ..The same program will continue working or reinstallation is required? @shiftcodeYT

**Comment by Doniiie** [comment] 2016-08-04 19:51
@shiftcodeYT I just want to say that u r doing a really gr8 job , tnx

**Comment by shiftcodeYT** [comment] 2016-08-04 19:52
@Doniiie thank you :)

**Comment by shiftcodeYT** [comment] 2016-08-04 19:53
@Shankky14 you will have to redownload. But it isn't fixed yet anyways

**Comment by Shankky14** [comment] 2016-08-04 19:59
Okay☺ ..btw thanx for your hardwork!

**Comment by Albanerr** [comment] 2016-08-04 20:08
how much time we should wait ? thanks for your hard work

**Comment by shiftcodeYT** [comment] 2016-08-04 20:09
@Albanerr until it's fixed. ETA: impossible to say

**Comment by Ytkevtek** [comment] 2016-08-04 21:45
you are finish to fix? @shiftcodeYT

**Comment by gulugulux** [comment] 2016-08-04 21:55
i take error that we can't find any pokestop. When is this error fixed? Can someone tell me*

**Comment by Alexandr24** [comment] 2016-08-04 22:03
@gulugulux until it's fixed. ETA: impossible to say
unknown6...

**Comment by itskaje** [comment] 2016-08-04 23:43
@Ytkevtek @gulugulux When its fixed im sure shiftcodeYT will write something on the front page and also say something here in comments that it is fixed. Please wait patiently like the rest of us. This is not a easy fix. ALL bots everywhere for Pokemon Go stopped working because of the new update. Some posts on other forums say that this new update on Pokemon Go made the bot we had useless and therefor they have to make a totally new bot. So you can just imagine how long it takes to make a new bot... its not something that can be done in a few hours.  PLEASE stop asking if the bot is fixed... just keep refreshing this page to see if swiftcodeYT says anything about it being fixed and ready for use. 

Remember its a privilege to use this bot... NOT a birthright. 
~wait patiently

**Comment by toxicflash** [comment] 2016-08-05 02:04
How do i get this bot?

**Comment by itskaje** [comment] 2016-08-05 02:14
@toxicflash look at the comment above yours. Next time read before you comment and ask for help.

**Comment by FallenDev** [comment] 2016-08-05 02:47
@Shankky14 you'll need to download the newest compiled version. As you should be doing daily.

**Comment by marsekalchasa** [comment] 2016-08-05 02:58
Keep Fight !! you can Solve This Problem Admin.....

**Comment by LordSad** [comment] 2016-08-05 03:17
I would just like to say that the devs here are doing a stand up job.... i made a bot the first time pokemon go came out and gave up on updates as soon as the first change came.... people should think of that before complaining

**Comment by WhySoSerious21** [comment] 2016-08-05 03:23
@LordSad wkwk :D yaa, nowadays, people do some complaining without thinking

**Comment by jedi2003** [comment] 2016-08-05 04:35
@shiftcodeYT  thx your hard work

**Comment by redafad** [comment] 2016-08-05 22:11
https://github.com/Mila432

**Comment by JustinCR20** [comment] 2016-08-05 22:18
and whats that? sorry im noob :V

**Comment by redafad** [comment] 2016-08-05 22:19
idk just a link that might help the OP ignore it lol

**Comment by JustinCR20** [comment] 2016-08-05 22:20
ok

**Comment by Shankky14** [comment] 2016-08-06 20:50
Guyss...How long its gonna take..I have never used a bot before...and when I thought of it...Niantic changes its API!

**Comment by shiftcodeYT** [comment] 2016-08-06 20:51
@Shankky14 All the fields have been found, now it's on testing and implementing.

**Comment by Shankky14** [comment] 2016-08-06 20:53
Hoping to get the bot soon☺

**Comment by FallenDev** [comment] 2016-08-06 21:42
Soon @Shankky14 , @shiftcodeYT and @BukkitTNT will be doing the main implementations. Stay tuned.

**Comment by nemezis49** [comment] 2016-08-06 23:38
How long we must waiting guys ?

**Comment by spot88** [comment] 2016-08-06 23:47
@nemezis49 as long as it takes.

**Comment by allanrodrigues89088** [comment] 2016-08-07 06:57
the bot 're working? mine was showing it , we can not find any pokestop in 5000 m

**Comment by WhySoSerious21** [comment] 2016-08-07 06:58
@allanrodrigues89088 dude pls, scroll up and read all of the comments, and pls read before comment :)

**Comment by ShitsMoneyOnBotDevs** [comment] 2016-08-07 08:00
Shiftcode, which country are you from?

**Comment by allanrodrigues89088** [comment] 2016-08-07 08:23
I'm in Brazil , rio de janeiro , if anyone can help me plz

**Comment by darcsacka** [comment] 2016-08-07 11:11
NEW API WORKING, as said by reddit teaam wich worked on this
https://m.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/?utm_source=mweb_redirect&compact=true

https://github.com/keyphact/pgoapi

**Comment by darcsacka** [comment] 2016-08-07 11:49
i don't want to spoil the fun, but there are bot that already function, but i wont write it here. I really liked this bot, can you please hurry?

**Comment by STAMIL0** [comment] 2016-08-07 14:40
@shiftcodeYT hello, can you giva an update about the ETC. 

Thankyou

**Comment by Deantje2016** [comment] 2016-08-07 14:44
Guys hold on he does this for us in his spare time. Understand that his life is not only about this bot. He got his own personal life too. Keep that in mind. He is doing all he can.

**Comment by STAMIL0** [comment] 2016-08-07 15:06
you are right, but he has to understand that he is the pokebot uber master. ;-)

**Comment by STAMIL0** [comment] 2016-08-07 15:15
a smal update would be super nice, we are the loyal followers of SC. instead of @darcsacka spoiling al off the fun here with his betrayal. ;-p

**Comment by darcsacka** [comment] 2016-08-07 15:16
who said that i am using other ones dude. and i think the biggest betrayal was to post the links to the working api. =]]

**Comment by gulugulux** [comment] 2016-08-07 15:28
Can someone send me a working BOT programme link??

**Comment by darcsacka** [comment] 2016-08-07 15:47
google is your friend

**Comment by gulugulux** [comment] 2016-08-07 16:00
@darcsacka you are so clever. I couldn't think doing this. I couldn't find any link about working bot programme.

**Comment by darcsacka** [comment] 2016-08-07 16:40
than you don't deserve to use a bot, if you are not able to proper google stuff.

**Comment by darcsacka** [comment] 2016-08-07 16:41
it is not polite to advertise another ones bot in here you nice human being.

**Comment by gulugulux** [comment] 2016-08-07 17:09
I don't care you @darcsacka ! Stop mentionning with me.

**Comment by nemezis49** [comment] 2016-08-07 17:17
Good job guys.

**Comment by darcsacka** [comment] 2016-08-07 17:17
little kid, please learn some English first. The key to your question is  https://github.com/shiftcodeYT/PokeBot3 here you little punk. It's in the first freaking link.
oh and by the way. you are the only one mentioning people @gulugulux.

**Comment by gulugulux** [comment] 2016-08-07 17:55
Idiot @darcsacka r u spelling guide? The fact that i am writing quickly, i can do some typographical error but you are so stupid as you didn't understand it.

**Comment by darcsacka** [comment] 2016-08-07 18:03
[OFFtopic]OK, i just reported you for insulting me. Next time please choose more appropriate words! This trash talk doesn't belong in here. Better say thank you for helping you out!. 

[ON topic] - any news from shiftcode?

**Comment by gulugulux** [comment] 2016-08-07 18:05
Fuck off @darcsacka

**Comment by darcsacka** [comment] 2016-08-07 18:07
right, like I am listening to what you order me or something. I shall make another report if you continue to talk that way.

**Comment by gulugulux** [comment] 2016-08-07 18:11
The most idiot human i have ever seen @darcsacka

**Comment by shiftcodeYT** [comment] 2016-08-07 18:12
@darcsacka I'm close. Release ETA is tomorrow evening, GMT+1 (where it is 20:12 right now)

**Comment by darcsacka** [comment] 2016-08-07 18:13
thank you for the answer shiftcode :100:

**Comment by C3rberus9** [comment] 2016-08-07 18:59
Cool! I looked after other bots too, as maybe the most of you, but this one
is the most configurable, and I like it too tho...
So I stayed calm, and I am still waiting till you get this bot to an update
which one is working again properly.

Keep it up man!

2016-08-07 20:13 GMT+02:00 darcsacka <notifications@github.com>:

**Comment by Doniiie** [comment] 2016-08-07 21:33
@shiftcodeYT nice work man, keep it up

**Comment by Bruschetta987** [comment] 2016-08-08 09:48
@shiftcodeYT Good Job man, post link when you've released the ETA.
Love you <3

**Comment by itskaje** [comment] 2016-08-08 15:34
Guy, stop rushing swiftcodeYT. Trust me, it's best that he takes his time and work on the boy properly than for you to have a half working bot.  ShiftcodeYT is great at what he's doing and as long as you don't rush him you know you will get a great bot in the end. Rush him and you will get a bot with a million errors to which he would have to release more bots and you'd have to download and install and setup over and over. 

PLEASE wait patiently! 100% finished product is better than 90%.

**Comment by ShitsMoneyOnBotDevs** [comment] 2016-08-08 17:01
@itskaje what the fuck are you talking about? They all thank him for his project. No one said: gimme the bot nao

**Comment by Deantje2016** [comment] 2016-08-08 17:08
Just all hush and stop replying until he is posting something about the bot.

**Comment by ShitsMoneyOnBotDevs** [comment] 2016-08-08 17:18
Pimmel okay

**Comment by FallenDev** [comment] 2016-08-08 17:33
Do I have to moderate this post as well? Please keep it civil! We've already fixed the API, that's not the problem. The problem is we're rebuilding the Graphical User Interface (GUI) from the ground up, and we're reconnecting it to the API. Since there are new API calls and such. We have to recreate logic to that. It's quite the process. Myself and the other dev's also work during the day. So this is during our personal time. Unlike other communities that have 30+ dev's. So please be patient. We'll address it shortly.

**Comment by itskaje** [comment] 2016-08-08 18:08
@ShitsMoneyOnBotDevs  No need to swear or get worked up. I was not directing that message on you or anyone specifically I just simply saying in general for people to stay calm a dickhead just wait patiently without asking when it will be done. As you can see when you scroll up I'm the one who started this post and I'm getting emails whenever people message on this post and it's quite annoying seeing people ask when the bot will be done as if they paid for its development. And please do not swear at me again.

**Comment by ShitsMoneyOnBotDevs** [comment] 2016-08-08 18:09
May I sweat on you? @itskaje

**Comment by LordSad** [comment] 2016-08-08 19:22
Yes, plz start deleting some of these....I was wondering why you didn't do it before...

**Comment by shiftcodeYT** [comment] 2016-08-09 11:54
OK Guys, I have great news for you! A fixed version is done, it's currently being tested by donators. Public release should be coming today. [GMT+1] [around 6-8pm]

**Comment by shiftcodeYT** [comment] 2016-08-09 14:12
Fixed guys. Download [here](https://github.com/shiftcodeYT/PokeBot3/releases/latest)

**Closed by shiftcodeYT** 2016-08-09 14:12 UTC
Labels: bug, in progress, priority
